# https://wiki.archlinux.org/index.php/Network_configuration
network:
  hostname: soft022-009
  interfaces:
    #- { name: 'enp0s3', address: 'dhcp' }
    - { name: 'enp0s3', address: '172.23.22.9/24', gateway: '172.23.22.254' }
  # suppress it to use dns provided by isp. Configs /etc/resolv.conf
  dns:
    search: softplan.com.br
    nameservers:
      - 172.23.1.1
      - 172.23.1.10

# https://wiki.archlinux.org/index.php/beginners%27_guide#Prepare_the_storage_devices
storage:
  # partition table for device /dev/sda. Use lsblk to know the disks available.
  name: /dev/sda
  volumes:
    - { size: '4g', type: 'swap' }
    - { size: '512m', type: 'ext4', mount: '/boot' }
    - { size: '80G', type: 'ext4', mount: '/' }
    - { size: '100%FREE', type: 'ext4', mount: '/home' }


# https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
locale:
  # languages to be enabled. Note that the first one will be exported to LANG: https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
  languages:
    - 'en_US.UTF-8 UTF-8'
  keymap: br-abnt2
  font: Lat2-Terminus16
  timezone: Brazil/East

#  User section, instructions, please note the following:
#  - Most params are managed by ansible users module: http://docs.ansible.com/user_module.html
#  - The 'sudo' special param may have the following values: no (default), yes (allows sudo with password) and passwordless (allows sudo without informing password)
#  - The 'root' user allows a special param named 'ssh', which enables (or disables) ssh login. Default is 'no'.
users:
  - { name: 'root', ssh: 'no', password: '$6$rounds=100000$WyP5nxv.aJO1.SQ1$uKJnrcDTzpI1hkAEErsBGH3AFuMpGCcW2d8zIMX5ClFSLQlcUbssq6q9iIjdjf1GNBveE6g5xIonyOrD82abA0' }
  - { name: 'luciano', groups: 'adm,users,docker', sudo: 'passwordless', password: '$6$rounds=656000$7JlPYLVcnGL6LGGj$UB61v779Lzd05836UGeEjb8JycHj/g4BmzV8UHt.tGP.pWNxusFxvgGzhJ9luFehlqzHFi9RThPWvKJtV65dt0' }

# https://wiki.archlinux.org/index.php/Samba#Client_configuration
# samba:
#   mount:
#     - { path: '/mnt/empresa', src: '//softplan.com.br/empresa', username: 'sajwebversao', password: 'Softplan2012' }
#     - { path: '/mnt/O', src: '//server21.softplan.com.br/O', username: 'sajwebversao', password: 'Softplan2012' }
#     - { path: '/mnt/sajwebdev', src: '//sajwebdev.softplan.com.br/instaladores', username: 'sajwebversao', password: 'Softplan2012' }

packages:
  # https://www.archlinux.org/packages/
  official:
    - vim
    - nano
    - wget
    - curl
    - zsh
    - xf86-video-intel
    - gnome
    - docker
    - rdesktop
    - alsa-utils
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
    - zip
    - unzip
    - tar
    - vagrant
    - chromium
    - terminator
    - sshfs
    - gvfs
    - gvfs-smb
    - cmus
    - remmina
    - libmad
    - firefox
    - xulrunner
    - pulseaudio
    - pulseaudio-alsa
    - pavucontrol
    - python-pip
    - linphone
    - pgadmin3
    - maven
    - npm
    - mpc
    - acpi
    - xclip
  aur:
    - atom-editor
    - powerline-fonts-git
    - virtualbox-ext-oracle
    - jdk7
    - jdk

# Will enable services on boot
services:
  - docker
  - gdm
